image: maven:3-jdk-8-slim

stages:
  - build
  - package 
  - deploy

.default_cache: &default_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository/
    - target

version:
  stage: .pre
  image: registry.gitlab.com/juhani/go-semrel-gitlab:v0.21.1
  before_script:
  - apt update
  - apt install --no-install-recommends -y git
  - git fetch --tags
  script:
    - release --bump-patch next-version > .next-version
    - cat .next-version
  artifacts:
    paths:
    - .next-version
  except:
    - tags

build:
  stage: build
  cache:
    << : *default_cache
    policy: pull-push
  script:
    - mvn clean
    - export RELEASE_VERSION=$(<.next-version)
    - mvn versions:set -DnewVersion=$RELEASE_VERSION -DprocessAllModules
    - mvn $MAVEN_CLI_OPTS compile
  artifacts:
    paths:
    - pom.xml
  except:
    - tags

package:
  stage: package
  cache:
    << : *default_cache
    policy: pull-push
  script:
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths:
    - target/starryheavens-*-jar-with-dependencies.jar
  except:
    - tags

deploy:
  stage: deploy
  cache:
    << : *default_cache
    policy: pull
  environment:
    name: github-registry
  script:
    - mvn $MAVEN_CLI_OPTS deploy D-registry=https://maven.pkg.github.com/${gituser} -Dtoken=${gittoken}
  except:
    - tags

version_tag:
  stage: deploy
  image: registry.gitlab.com/juhani/go-semrel-gitlab:v0.21.1
  before_script:
  - apt update
  - apt install --no-install-recommends -y git
  - git fetch --tags
  script:
    - echo "RELEASE_URL=https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/$CI_JOB_ID/artifacts/release" > build_info
    - echo "RELEASE_DESC=\"$(uname -mo) binary\"" >> build_info
    - echo "RELEASE_SHA=$CI_COMMIT_SHA" >> build_info
    - echo "RELEASE_VERSION=$(<.next-version)" >> build_info
    - export RELEASE_VERSION=$(cat .next-version)
    - rm -f release_info
    - mv build_info release_info
    - . release_info
    - echo -n "Updating version information v$RELEASE_VERSION ..."
    - release changelog
    - release commit-and-tag CHANGELOG.md release_info
    - release --ci-commit-tag v$RELEASE_VERSION add-download-link --name release --url $RELEASE_URL --description "$RELEASE_DESC"
  except:
    - tags
 